In [3]:
import numpy as np

In [5]:
m = np.array([1, 3, 2, 0])
m

array([1, 3, 2, 0])

In [6]:
m.shape

(4,)

In [13]:
m = m.astype(np.int8)
m.dtype

dtype('int8')

In [17]:
m = np.array([[1, 5], [4, 0]])
m.shape

(2, 2)

In [18]:
m = np.ones((3, 5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
m = np.random.random((4, 3))
m

array([[0.10044029, 0.78285271, 0.40556377],
       [0.65227674, 0.69052785, 0.31342348],
       [0.67566601, 0.16618213, 0.56657317],
       [0.67042319, 0.56563894, 0.02411613]])

In [28]:
m[m < 0.5]

array([0.10044029, 0.40556377, 0.31342348, 0.16618213, 0.02411613])

In [30]:
(m > 0.7) | (m < 0.2)

array([[ True,  True, False],
       [False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
m.ravel()

array([0.10044029, 0.78285271, 0.40556377, 0.65227674, 0.69052785,
       0.31342348, 0.67566601, 0.16618213, 0.56657317, 0.67042319,
       0.56563894, 0.02411613])

In [33]:
m.reshape((2, 6))

array([[0.10044029, 0.78285271, 0.40556377, 0.65227674, 0.69052785,
        0.31342348],
       [0.67566601, 0.16618213, 0.56657317, 0.67042319, 0.56563894,
        0.02411613]])

In [42]:
a = m.T.reshape((6, 2))
a = a.T

In [46]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape((1, 6))

In [47]:
a + b

array([[1.10044029, 2.67566601, 3.78285271, 4.16618213, 5.40556377,
        6.56657317],
       [1.65227674, 2.67042319, 3.69052785, 4.56563894, 5.31342348,
        6.02411613]])

In [48]:
a * b

array([[0.10044029, 1.35133202, 2.34855812, 0.66472851, 2.02781884,
        3.399439  ],
       [0.65227674, 1.34084638, 2.07158354, 2.26255576, 1.56711741,
        0.14469678]])

In [51]:
b = b.reshape((6, 1))

In [52]:
a.dot(b)

array([[9.89231679],
       [8.0390766 ]])